[project]
name = "opencv-1"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9.6"
dependencies = [
    "face-recognition>=1.3.0",
    "face-recognition-models>=0.3.0",
    "mediapipe>=0.10.21",
    "pip>=25.3",
    "requests>=2.32.5",
]
